"""init tables

Revision ID: a1ba80310893
Revises:
Create Date: 2024-08-07 21:47:35.863910

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a1ba80310893"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "profile",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("first_name", sa.String(), nullable=False),
        sa.Column("last_name", sa.String(), nullable=False),
        sa.Column("profession", sa.String(), nullable=False),
        sa.Column("balance", sa.Numeric(), nullable=False),
        sa.Column("type", sa.Enum("client", "contractor", name="profiletype"), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_profile")),
    )
    op.create_table(
        "contract",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("terms", sa.String(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("new", "in_progress", "terminated", name="contractstatus"),
            nullable=False,
        ),
        sa.Column("client_id", sa.Integer(), nullable=False),
        sa.Column("contractor_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["client_id"], ["profile.id"], name=op.f("fk_contract_client_id_profile")
        ),
        sa.ForeignKeyConstraint(
            ["contractor_id"], ["profile.id"], name=op.f("fk_contract_contractor_id_profile")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_contract")),
    )
    op.create_table(
        "job",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("price", sa.Numeric(), nullable=False),
        sa.Column("paid", sa.Boolean(), nullable=False),
        sa.Column("payment_date", sa.DateTime(), nullable=True),
        sa.Column("contract_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["contract_id"], ["contract.id"], name=op.f("fk_job_contract_id_contract")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job")),
    )
    op.drop_table("test_item")
    op.drop_table("test_profile")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "test_profile",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("first_name", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("last_name", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("profession", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "balance", sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False
        ),
        sa.Column(
            "type",
            postgresql.ENUM("client", "contractor", name="profile_type"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.Column("updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    )
    op.create_table(
        "test_item",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("note", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    )
    op.drop_table("job")
    op.drop_table("contract")
    op.drop_table("profile")
    # ### end Alembic commands ###
